CREATE DATABASE HORARIOS;
USE HORARIOS;

CREATE TABLE ALUMNO (
    ID_ALUMNO INT PRIMARY KEY NOT NULL, 
    NOMBRE_ALUMNO VARCHAR (50),
    EDAD_ALUMNO INT
);

CREATE TABLE ASIGNATURA (
    ID_ASIGNATURA INT PRIMARY KEY NOT NULL,
    NOMBRE_ASIGNATURA VARCHAR (30),
    HRS_SEMANA INT,
    MODALIDAD VARCHAR (20)

);

CREATE TABLE PERSONAL (
    ID_PERSONAL INT PRIMARY KEY NOT NULL,
    NOMBRE_PERSONAL VARCHAR (50), 
    CARGO VARCHAR (30)

);

CREATE TABLE CURSO (
    ID_CURSO INT PRIMARY KEY NOT NULL,
    ID_ASIGNATURA INT, CONSTRAINT FK_ASIGNATURA FOREIGN KEY (ID_ASIGNATURA) REFERENCES ASIGNATURA (ID_ASIGNATURA),
    ID_PERSONAL INT, CONSTRAINT FK_PERSONAL FOREIGN KEY (ID_PERSONAL) REFERENCES PERSONAL (ID_PERSONAL),
    ESPACIO VARCHAR (30)

);

CREATE TABLE GRUPO (
    ID_GRUPO INT PRIMARY KEY NOT NULL,
    ID_ALUMNO INT, CONSTRAINT FK_ALUMNO FOREIGN KEY (ID_ALUMNO) REFERENCES ALUMNO (ID_ALUMNO),
    ALUMNO_1 INT,
    ALUMNO_2 INT,
    ALUMNO_3 INT,
    ALUMNO_4 INT,
    ALUMNO_5 INT,
    ALUMNO_6 INT,
    ALUMNO_7 INT,
    ALUMNO_8 INT,
    ALUMNO_9 INT,
    ALUMNO_10 INT,
    ID_CURSO INT, CONSTRAINT FK_CURSO FOREIGN KEY (ID_CURSO) REFERENCES CURSO (ID_CURSO)
);

ALTER TABLE CURSO ADD HORARIO VARCHAR (30);